site_name: AndyWebServices Documentation
site_url: https://docs.andywebservices.com
theme:
  name: material
  logo: assets/logo.png
  palette:
    primary: red
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
